# https://hub.docker.com/_/ubuntu
FROM ubuntu:latest
LABEL org.opencontainers.image.authors="githubfoam"

WORKDIR /tmp

RUN apt-get update -qy && \ 
    apt-get dist-upgrade -yq && \
    apt-get purge unattended-upgrades && \
    apt-get clean all
    

# Create user and set ownership and permissions as required
RUN adduser -D myuser && chown -R myuser /myapp-data

USER myuser
