name: "hping3 CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  ubuntu-hping3-job:
    name: "docker ubuntu hping3 ubuntu 20.04"
    runs-on: ubuntu-latest
    env:
      distribution: "archlinux" #https://hub.docker.com/_/archlinux
      version: "latest"
      name: "archlinux:ansible"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch  
    - name: "docker build ubuntu hping3"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ubuntu:netsec . --file dockerfiles/Dockerfile.ubuntu2104.networksecurity 
        docker image ls
        docker image history ubuntu:netsec
        docker system df -v               
        docker image inspect ubuntu:netsec
