name: "matrix docker ubuntu latest CI workflow"


on:
  push:
    branches: [ test ]
  # schedule:
  #     - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month 


jobs:

  ubuntu-latest-job:
    name: "docker ubuntu latest"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
         - sshfs
         - ssh 
         - remora
         - zram
         - xanmod
         - modsecurity
    env:
      distribution: "ubuntu"
      version: "latest"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch       
    - name: "run test"
      run: |
        dir=$(pwd)
        cd $dir/dockerfiles/ubuntu/latest
        cd ${{matrix.node}}
        echo "############################################"
        echo "############################################"
        echo "Building  ${{matrix.node}} dockerfile"
        echo "############################################"
        echo "############################################"        
        docker build -t ${distribution}/${{matrix.node}}${version} .  
        # docker image ls
        # docker image history ${distribution}/${{matrix.node}}${version}
        # docker system df -v               
        # docker image inspect ${distribution}/${{matrix.node}}${version}           
